title: COVID Kokua
description: Varying information about COVID related resources.
google_analytics:
show_downloads: false
theme: jekyll-theme-merlot
github:
  is_project_page: true
  repository_url:  https://github.com/covid-kokua/covid-kokua.github.io
gems:
  - jekyll-mentions
